### ISSUE TITLE
Creating Student Model

### ISSUE THREAD

**Issue by Foodiekid** [AlekyaPochampally/mvc-app#2]

**Comment by Foodiekid** [comment]
- [x] creating the model (and properties)
- [x] creating sample data that fits the model
- [x] seeding your sample data
- [ ] routing requests to your controller
- [ ] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)
- [ ] implementing implementing the five views used to list all/create/read/update/delete (CRUD).
- [ ] update the application navigation to provide access to your resource
- [ ] update the application navigation to provide access to your developer page.
- [x]  Resolve merge conflicts if occurred
- [x] Push the updated code

**Comment by AlekyaPochampally** [comment]
completed the above checked items
