### ISSUE TITLE
Create Teacher Model

### ISSUE THREAD

**Issue by AlekyaPochampally** [AlekyaPochampally/mvc-app#4]

**Comment by chandu7766** [comment]
- [x] creating the model (and properties).

- [x] creating sample data that fits the model,

- [x] seeding your sample data

- [ ] routing requests to your controller

- [ ] implementing your controller (2 json calls, 5 view requests, 3 data actions (create/update/delete)

- [ ] implementing implementing the five views used to list all/create/read/update/delete (CRUD).

- [ ] update the application navigation to provide access to your resource 

-  [ ] update the application navigation to provide access to your developer page.

- [ ] verifying routing model controller

- [ ] Testing the Final.

**Comment by chandu7766** [comment]
completed the above three tasks and checked them.
